--- 
web-testing: 
  script: 
    - "echo running web tests"
    - cd exercise-web
    - npm run build
    - npm test
  tags: 
    - ci
api-testing: 
  script: 
    - "echo running api tests"
    - pip install django
  tags: 
    - ci