image: node:12.15.0

web-testing: 
  script: 
    - "echo running web tests"
    - cd exercise-web
    - npm install
    - npm run build
    - npm test
  tags: 
    - ci

api-testing: 
  script: 
    - "echo running api tests"
    - python manage.py check
  tags: 
    - ci